services:
  speedtest:
    build:
      context: .
      target: docker-speedtest-telegraf

    environment:
      - REMOTE_WRITE_ENDPOINT
      - METRICS_INSTANCE_ID
      - GRAFANA_API_KEY
      - CHECK_INTERVAL=30m
